### ISSUE TITLE
CSS3 新增calc(...)的使用

### ISSUE THREAD

**Issue by hexson** [hexson/hexson.github.io#12]
CSS3新增函数 `calc()` 可以用在任何一个需要计算长度、频次、角度、时间、数值、或整型的地方，有了 `calc()`，你就可以通过计算来决定一个CSS属性的值了。

### 语法

```css
/* property: calc(expression) */
width: calc(100% - 10px);
```

#### 值

expression 一个数学表达式，该表达式的结果会作为最终的值。

#### 表达式

该表达式可以使用以下运算符任意组合（使用正常的运算符优先级顺序）。

`+` 加 `-` 减 `*` 乘 `/` 除

表达式中的操作数可以使用任意语法种类的长度。如果你愿意，你可以在一个表达式中混用多种不同的长度单位。在需要时，你还可以使用小括号来调整计算顺序。

> 注：乘数中至少要有一个及被除数必须是 <number> 类型的，用0作除数会让HTML解析器抛出异常。

> 注：+和-运算符的两边必须始终要有空白符。比如calc(50% -8px)会被解析成为一个无效的表达式：一个百分比后跟一个负数长度值。而calc(8px + -50%)会被解析成为一个长度后跟一个加号再跟一个负百分比。*和/运算符不需要空白符，但考虑到统一性，仍然推荐加上空白符。

> 实际使用时，需要添加浏览器的前缀 `-webkit-calc(...)` `-moz-calc(...)`

### 示例

```css
.example {
  /* 设置.example宽度为 容器宽度减去10px 后的值 */
  width: calc(100% - 10px);
  /* 设置.example宽度为 容器宽度的10%加上10em 后的值 */
  width: calc(10% + 10em);
  /* 设置.example宽度为 容器宽度的20%乘以5 后的值(值为100%) */
  width: calc(20% * 5);
  /* 设置.example宽度为 容器宽度除以5 后的值(值为20%) */
  width: calc(100% / 5);
  /* 设置.example宽度为 100减去(60减去10)px 后的值(值为50px) */
  width: calc(100px - calc(60px - 10px));
}
```

### 兼容性

[CSS3 新增calc(...)的兼容性](http://hexson.win/#/article/13)
