### ISSUE TITLE
CSS 字体大小之REM

### ISSUE THREAD

**Issue by hexson** [hexson/hexson.github.io#5]
网页技术发展至今，随着设备平台等的迅速发展，相关技术迭代的也很迅猛，`CSS3` 的出现，网页字体大小从之前的 `px` 、 `pt` 、 `em` 等衍生了一个新的单位 `rem`。

**W3C** 上用一句话描述了一下它：font size of the root element

从这句话上面看，我们只要在根元素 `<html>` 设定一个参考值，然后再根据需要具体的去设置对应的字体大小，我们来看一个实例代码：

```css
html {
  font-size: 62.5%;  /* 10px */
}
p,span {
  font-size: 1.4rem; /* 14px */
}
.class {
  font-size: 1.8rem; /* 18px */
}
```

我们来解析一下这段代码的意思，首页给根元素 `<html>` 设置了字体的大小10px，这个数值是怎么来的呢？浏览器默认字体大小16px * ? = 10px，我们可以得出具体的百分比，然后给元素 `<p>` 和 `<span>` 设置的字体大小为 1.4 * 10px = 14px，给某个或某些 **className** 包含 `.class` 的元素设置字体大小为 1.8 * 10px = 18px，到此为止，你知道该怎么去使用rem了吧。

> **em** 虽然一般以元素 `<body>` 为参考点，但是某些时候你如果不知道父元素字体大小，那么很可能子元素的字体大小是未知的。附上 **em** 的计算公式：

> 1 / 父元素的font-size × 需要转换的像素值 = em值
